<a href="https://colab.research.google.com/github/hyunkoome/DL_Study/blob/dev/DL_Basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!nvidia-smi

Mon Feb  3 02:08:16 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   38C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [2]:
!nvcc -V

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Thu_Jun__6_02:18:23_PDT_2024
Cuda compilation tools, release 12.5, V12.5.82
Build cuda_12.5.r12.5/compiler.34385749_0


In [3]:
!pip3 install torch torchvision torchaudio

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 4.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 70.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 19.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 54.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 2.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 5.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 11.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 7.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 6.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 51.6 MB/s eta 0:00:00
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjitlin

## **1. pytorch tensor 기본 연산**

In [4]:
import torch

In [9]:
x = torch.tensor([[1,0], [0, 1]], dtype=torch.float32)
y = torch.tensor([[5,6], [7, 8]], dtype=torch.float32)

# basic op
print(x+y)
print(x-y)
print(x * y) # multiple: element-wise
print(x @ y) # multiple

tensor([[6., 6.],
        [7., 9.]])
tensor([[-4., -6.],
        [-7., -7.]])
tensor([[5., 0.],
        [0., 8.]])
tensor([[5., 6.],
        [7., 8.]])


**ex01) 랜덤한 텐서 (3, 3)을 생성하고, 정규화를 수행하는 코드를 작성해 봐.**

In [16]:
import torch
import numpy as np

# create random tensor
random_tensor = torch.rand(3, 3, dtype=torch.float32)
print(random_tensor)

# min-max normalization
min_val = random_tensor.min()
max_val = random_tensor.max()
normalized_tensor = (random_tensor-min_val)/(max_val-min_val)
print(normalized_tensor)

tensor([[0.7960, 0.9164, 0.5767],
        [0.0654, 0.5653, 0.2052],
        [0.4380, 0.4607, 0.7325]])
tensor([[0.8586, 1.0000, 0.6008],
        [0.0000, 0.5875, 0.1643],
        [0.4379, 0.4645, 0.7839]])


## **2. pytorch Autograd 자동 미분**

In [17]:
# requres_grad=True 설정 시, 자동 미분

a = torch.tensor(2.0, requires_grad=True)
b = torch.tensor(3.0, requires_grad=True)

y = a**2 + b**3
y.backward()

print(a.grad) # dy/da
print(b.grad) # dy/db

tensor(4.)
tensor(27.)


**ex02) f(x) = x^3 + 2x^2 + 5x + 1 의 도함수를 자동 미분으로 구해보자.**

In [19]:
import torch
import numpy as np

x = torch.tensor(2.0, requires_grad=True)

f_x = x**3 + 2*x**2 + 5*x + 1
f_x.backward()

print(f"f'(x) at x=2: {x.grad}") # d f_x /dx

f'(x) at x=2: 25.0
